name: flipper_services
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"
 
dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.3
  #local package
  google_fonts:  
  geolocator: 
  permission_handler: 
  
  redux: 
  flutter_redux: 
  flutter_masked_text: 
  built_value: 
  image_picker: 
  built_collection: 
  # flutter_date_pickers: ^0.0.6
  # flutter_material_color_picker: ^0.0.5
  flutter_image_compress: 
  # tabbar: 
  intl: 
  jiffy: 
  expandable: 
  # syncfusion_flutter_charts: ^18.3.44
  
  uuid: 
  
  timezone: 
  # this will deprecate soon do not use them
  # flutter_barcode_scanner: 
  # flipper_ui: ^1.0.0
  
  # rubber: ^0.4.0
  get_storage:  #replaced shared_preferences because shared_preferences is slow
  country_picker: 
  # background_fetch: 0.6.0
  # social sign in
  firebase_auth: 
  # end social signin
  firebase_core: 
  cloud_firestore: 
  firebase_messaging: 
  firebase_analytics: 
  camera: 
  # flutter_uploader:
  rxdart: 
  # loading: 
  # firebase_crashlytics: "^0.4.0"
  logger: 
  async: 
  # filledstacks | state management
  stacked: 
  stacked_hooks: 

  stacked_services: 
  # get it
  get_it: 
  injectable:
  # provider
  provider: 
  cached_network_image: 
  # flutter_dotenv: ^2.1.0
  mailer: ^3.2.1
  contacts_service: ^0.4.6
  # flutter_reactive_ble: ^2.5.3
  # flutter_text_drawable: ^0.3.1
  connectivity: 
  # background_fetch: '^0.5.1'
  # flutter_icons: ^1.1.0
  
  # bluetooth_thermal_printer: ^0.0.4
  # esc_pos_utils: ^0.4.9
  awesome_notifications: 
  # pusher: ^1.0.0
 
  couchbase_lite_dart: 
  path_provider: 
  # flipper_models:
  #   path:
  #     '../flipper_models'
  # firebase_dynamic_links: ^0.5.0+11
  share: 
  cron: 
  # firebase_remote_config: ^0.6.0
  # pusher_websocket_flutter: ^0.2.0
  # pusher_beams: "^0.5.3+3"
dev_dependencies:
  test_coverage: 
  build_runner: 
  analyzer:
  built_value_generator:
  auto_route_generator: 
  injectable_generator:
  mockito:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

