name: Deploy to web
on:
  pull_request:
    branches: [mobile]
  # Enable manual run
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (staging OR prod)"
        required: true
        default: "staging"
  # Refs/tags push events to matching v*, i.e. v1.0, v20.15.10
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Install web dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g firebase-tools

      # Checkout gallery code and get packages.
      - name: Checkout flipper code
        uses: actions/checkout@v2
      - run: git submodule update --init
      - run: flutter pub get

      # Build and deploy (by default, to staging).
      - run: flutter build  web --release
      - run: irebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
